name: MW - Clean up after PR is closed

on: 
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  remove-backend:
    uses: matfyz-sk/courses-backend/.github/workflows/remove-backend.yml@master
    with:
      BRANCH: ${GITHUB_HEAD_REF}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}