name: Deployment of backend

on:
  workflow_call:
    inputs:
      TAG:
        required: true
        type: string
      CONTAINER:
        required: true
        type: string
      BRANCH:
        required: true
        type: string
      BACKEND_PORT:
        required: true
        type: number
      VIRTUOSO_PORT:
        required: true
        type: number
      GRAPH_IRI_PREFIX:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true
      AUTH_SECRET:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: echo running on branch ${{ inputs.BRANCH }}
      - name: Running docker skript 
        uses: appleboy/ssh-action@master
        env:
          TAG: ${{ inputs.TAG }}
          CONTAINER: ${{ inputs.CONTAINER }}
          BACKEND_PORT: ${{ inputs.BACKEND_PORT }}
          VIRTUOSO_PORT: ${{ inputs.VIRTUOSO_PORT }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          GRAPH_IRI_PREFIX: ${{ inputs.GRAPH_IRI_PREFIX }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: TAG,CONTAINER,BACKEND_PORT,VIRTUOSO_PORT,AUTH_SECRET,GRAPH_IRI_PREFIX
          script: |
            docker build -t ${TAG} https://github.com/matfyz-sk/courses-backend.git
            docker stop ${CONTAINER}
            docker rm -f ${CONTAINER}
            docker run --detach --env "SPARQL_ENDPOINT=http://localhost:${VIRTUOSO_PORT}/sparql" --env "AUTH_SECRET=${AUTH_SECRET}" --env "GRAPH_IRI=https://${GRAPH_IRI_PREFIX}courses3.matfyz.sk/" --env "BASE_IRI=http://courses3.matfyz.sk/" --name=$CONTAINER --publish ${BACKEND_PORT}:3010 --restart=always ${TAG}
