name: Deployment of database

on:
  workflow_call:
    inputs:
      NAME:
        required: true
        type: string
      VIRTUOSO_PORT:
        required: true
        type: number
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true

jobs:
  database:
    runs-on: ubuntu-latest
    steps:
      - name: Running docker skript 
        uses: appleboy/ssh-action@master
        env:
          NAME: ${{ inputs.NAME }}
          VIRTUOSO_PORT: ${{ inputs.VIRTUOSO_PORT }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: NAME,VIRTUOSO_PORT
          script: |
            docker pull openlink/virtuoso-opensource-7
            mkdir /home/virtuoso/$NAME
            docker run -d --name $NAME --interactive --publish $VIRTUOSO_PORT:$VIRTUOSO_PORT --volume /home/virtuoso/$NAME:/database openlink/virtuoso-opensource-7:latest
            passwd=`(docker exec -i $NAME cat /settings/dba_password)`
            echo $passwd
            echo 'grant SPARQL_UPDATE to "SPARQL";' | docker exec -i $NAME isql 1111 dba $passwd
            
