name: Deployment of backend

on:
  workflow_call:
    inputs:
      BRANCH:
        required: true
        type: string
      BASE_BACKEND_PORT:
        required: true
        type: number
      BASE_VIRTUOSO_PORT:
        required: true
        type: number
      PR_NUMBER:
        required: false
        type: number
        default: 0
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true
      AUTH_SECRET:
        required: true
      DOCKERHUB_OWNER:
        required: true
      DOCKERHUB_ACCESS_TOKEN:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set TAG for backend docker image
        run: echo "TAG=courses:${{ inputs.BRANCH }}" >> $GITHUB_ENV
      - name: Set CONTAINER for backend docker container
        run: echo "CONTAINER=courses-${{ inputs.BRANCH }}" >> $GITHUB_ENV
      - name: Set GRAPH_IRI_PREFIX 
        if: ${{ inputs.BRANCH != 'master'}}
        run: echo "GRAPH_IRI_PREFIX=${{ inputs.BRANCH }}." >> $GITHUB_ENV
      - name: Set GRAPH_IRI_PREFIX 
        if: ${{ inputs.BRANCH == 'master'}}
        run: echo "GRAPH_IRI_PREFIX=" >> $GITHUB_ENV    
      - name: Set part of Virtuoso port
        run: echo "PR_PORT_PART=$(printf "%03i" ${{ inputs.PR_NUMBER }} | tail -c 4)" >> $GITHUB_ENV
      - name: Calculate Virtuoso port
        run: echo "VIRTUOSO_PORT=$(expr ${{ inputs.BASE_VIRTUOSO_PORT }} + ${{ env.PR_PORT_PART }})" >> $GITHUB_ENV
      - name: Calculate backend port
        run: echo "BACKEND_PORT=$(expr ${{ inputs.BASE_BACKEND_PORT }} + ${{ env.PR_PORT_PART }})" >> $GITHUB_ENV
      - name: PR port part
        run: echo "${{ env.TAG }}"
      - name: Virtuoso port
        run: echo "${{ env.CONTAINER }}"
      - name: Backend port
        run: echo "${{ env.GRAPH_IRI_PREFIX }}"
      - name: Deploy backend docker image
        uses: appleboy/ssh-action@master
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_OWNER }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          TAG: ${{ env.TAG }}
          CONTAINER: ${{ env.CONTAINER }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          BACKEND_PORT: ${{ env.BACKEND_PORT }}
          VIRTUOSO_PORT: ${{ env.VIRTUOSO_PORT }}
          GRAPH_IRI_PREFIX: ${{ env.GRAPH_IRI_PREFIX }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DOCKER_USER,DOCKER_PASS,TAG,CONTAINER,AUTH_SECRET,BACKEND_PORT,VIRTUOSO_PORT,GRAPH_IRI_PREFIX
          script: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASS}
            docker pull ricsitoth/${TAG}
            docker run --detach \
              --env "SPARQL_ENDPOINT=http://172.17.42.1:${VIRTUOSO_PORT}/sparql" \
              --env "AUTH_SECRET=${AUTH_SECRET}" \
              --env "GRAPH_IRI=https://${GRAPH_IRI_PREFIX}courses3.matfyz.sk/" \
              --env "BASE_IRI=https://courses3.matfyz.sk/" \
              --name=${CONTAINER} \
              --publish ${BACKEND_PORT}:3010 \
              --restart=unless-stopped \
              ${TAG}

