name: Deployment of database

on:
  workflow_call:
    inputs:
      NAME:
        required: true
        type: string
      PORT:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true

jobs:
  database:
    runs-on: ubuntu-latest
    steps:
      - name: Running docker skript 
        uses: appleboy/ssh-action@master
        env:
          NAME: ${{ inputs.NAME }}
          PORT: ${{ inputs.PORT }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: NAME,PORT
          script: |
            docker pull openlink/virtuoso-opensource-7
            mkdir /home/virtuoso/$NAME
            cd /home/virtuoso/$NAME
            docker run --name $NAME --interactive --tty --publish $PORT --volume /home/virtuoso/$NAME:/database openlink/virtuoso-opensource-7:latest
            passwd=`(docker exec -i -t $NAME cat /settings/dba_password)`
            docker exec -i -t $NAME isql 1111 dba $passwd
            grant SPARQL_UPDATE to "SPARQL";