name: Deployment of database

on:
  workflow_call:
    inputs:
      VIRTUOSO_NAME:
        required: true
        type: string
      VIRTUOSO_PORT:
        required: true
        type: number
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true

jobs:
  database:
    runs-on: ubuntu-latest
    steps:
      - name: Running docker skript 
        uses: appleboy/ssh-action@master
        env:
          VIRTUOSO_NAME: ${{ inputs.VIRTUOSO_NAME }}
          VIRTUOSO_PORT: ${{ inputs.VIRTUOSO_PORT }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: VIRTUOSO_NAME,VIRTUOSO_PORT
          script: |
            docker pull openlink/virtuoso-opensource-7
            mkdir /home/virtuoso/${VIRTUOSO_NAME}
            docker run --detach --name ${VIRTUOSO_NAME} --publish "172.17.42.1:${VIRTUOSO_PORT}:8890" --volume /home/virtuoso/${VIRTUOSO_NAME}:/database openlink/virtuoso-opensource-7:latest
            sleep 60
            passwd="$(docker exec ${VIRTUOSO_NAME} cat /settings/dba_password)"
            echo 'grant SPARQL_UPDATE to "SPARQL";' | docker exec ${VIRTUOSO_NAME} isql 1111 dba $passwd
            
