name: ci

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_OWNER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ricsitoth/courses:testing
      - name: Running docker skript 
        uses: appleboy/ssh-action@master
        env:
          USERNAME: ${{ secrets.DOCKERHUB_OWNER }}
          PASSWORD: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: USERNAME,PASSWORD
          script: |
            docker login --username $USERNAME --password $PASSWORD
            docker pull ricsitoth/courses:testing
            docker run -d --name=courses-testing --publish 5000:3010 --restart=always courses:testing

