name: ci

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to dockerhub
        run: docker login -u ${{ secrets.DOCKERHUB_OWNER }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: pwd
        run: pwd
      - name: Build Docker image
        run: docker build -f ./Dockerfile -t ricsitoth/courses:testing .
      - name: Push Docker image to DockerHub
        run: docker push ricsitoth/courses:testing
