name: MW - Trigger build of master frontend when labeled 'no frontend'

on: 
  pull_request:
    types: [labeled]
  workflow_dispatch:

jobs:
  create-frontend-directory:
    if: ${{ github.event.label.name == 'master frontend' }}
    uses: matfyz-sk/courses-frontend/.github/workflows/create-destination.yml@master
    with:
      FRONTEND_PATH: /home/www/devcourses3.matfyz.sk/
      PR_BRANCH: ${GITHUB_HEAD_REF}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
  deploy-master-frontend:
    needs: create-frontend-directory
    if: ${{ github.event.label.name == 'master frontend' }}
    uses: matfyz-sk/courses-frontend/.github/workflows/deploy.yml@master
    with:
      BRANCH: master
      FRONTEND_PATH: /home/www/devcourses3.matfyz.sk/
      BASE_WEBSITE_PORT: 8000
      PR_NUMBER: ${{ github.event.number }}
      PR_BRANCH: ${GITHUB_HEAD_REF}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      WEBSITE: ${{ secrets.WEBSITE }}
  config-apache:
    if: contains(github.event.pull_request.labels.*.name, 'master frontend')
    needs: [create-frontend-directory, deploy-master-frontend]
    uses: matfyz-sk/courses-frontend/.github/workflows/apache.yml@master
    with:
      BRANCH: ${GITHUB_HEAD_REF}
      PR_NUMBER: ${{ github.event.number }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}