name: MW - Building and deploying backend and database when PR is created

on: 
  pull_request:
    types: [opened, reopened, edited, synchronized]
  workflow_dispatch:

jobs:
  deploy-backend:
    uses: matfyz-sk/courses-backend/.github/workflows/old-deploy.yml@master
    with:
      BRANCH: ${GITHUB_HEAD_REF}
      BASE_BACKEND_PORT: 6000
      VIRTUOSO_PORT: 8890
      PR_NUMBER: ${{ github.event.number }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      IMPERSONATION_PASSWORD: ${{ secrets.IMPERSONATION_PASSWORD }}