name: release

env:
  TAG: courses:testing
  CONTAINER: courses-testing
  BRANCH: master

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Running docker skript 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker build -t $TAG git://github.com/matfyz-sk/courses-backend
            docker stop $CONTAINER
            docker rm -f $CONTAINER
            docker run -d --name=$CONTAINER -p 3010:3010 --restart=always $TAG

      
      

