name: release

on: 
  push:
    branches: [ master ]
    paths:
      - src/**
      - Dockerfile
      - package.json
      - package.json.lock
  workflow_dispatch:

jobs:
  release:
    uses: matfyz-sk/courses-backend/.github/workflows/deploy.yml@master
    with:
      TAG: courses:testing
      CONTAINER: courses-testing
      BRANCH: master
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      
      

