name: Removal of backend

on:
  workflow_call:
    inputs:
      BRANCH:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set CONTAINER for backend docker container
        run: echo "CONTAINER=courses-${{ inputs.BRANCH }}" >> $GITHUB_ENV
      - name: Remove backend docker container
        uses: appleboy/ssh-action@master
        env:
          CONTAINER: ${{ env.CONTAINER }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: CONTAINER
          script: |
            docker stop ${CONTAINER}
            docker rm -f ${CONTAINER}
