name: MW - Building and deploying an updated backend when PR has new commmits

on: 
  pull_request:
    types: [edited, synchronized]
  workflow_dispatch:

jobs:
  build-backend:
    uses: matfyz-sk/courses-backend/.github/workflows/build-push-backend.yml@master
    with:
      TAG: courses:${GITHUB_REF##*/}
    secrets:
      DOCKERHUB_OWNER: ${{ secrets.DOCKERHUB_OWNER }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  deploy-backend:
    needs: build-backend
    uses: matfyz-sk/courses-backend/.github/workflows/deploy-backend.yml@master
    with:
      TAG: courses:${GITHUB_REF##*/}
      CONTAINER: courses-${GITHUB_REF##*/}
      BASE_BACKEND_PORT: 6000
      BASE_VIRTUOSO_PORT: 7000
      PR_NUMBER: ${{ github.event.number }}
      GRAPH_IRI_PREFIX: ${GITHUB_REF##*/}.
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      DOCKERHUB_OWNER: ${{ secrets.DOCKERHUB_OWNER }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}


